### ISSUE TITLE
Not working in cythonized file

### ISSUE THREAD

**Issue by alex-eri** [hephex/asyncache#1]
Coro cached instead its result

```
Traceback (most recent call last):
  File "runner.py", line 4, in <module>
    asyncio.run(test.main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 11, in main
    await test(0)
RuntimeError: cannot reuse already awaited coroutine

```

test in attachments

```
python setup.py build_ext --inplace
python runner.py 
```

[test.zip](https://github.com/hephex/asyncache/files/5291707/test.zip)

**Comment by alex-eri** [comment]
Without `inspect.iscoroutinefunction(func)` works fine. Seems cython make its regular function returning Future.

**Comment by alex-eri** [comment]
https://github.com/cython/cython/issues/3849 upstream bug

**Comment by hephex** [comment]
This should be fixed now
